export const artworks = [
  { title: "Last day of pompeii", artist: "Jack Wolfstein", href: "/work.html" },
  { title: "The Great Wave off Kanagawa", artist: "Hokusai" },
  { title: "Starry Night", artist: "Vincent van Gogh" },
  { title: "Mona Lisa", artist: "Leonardo da Vinci" },
  { title: "The Persistence of Memory", artist: "Salvador Dalí" },
  { title: "The Scream", artist: "Edvard Munch" },
  { title: "The Night Watch", artist: "Rembrandt" },
  { title: "Girl with a Pearl Earring", artist: "Johannes Vermeer" },
  { title: "The Birth of Venus", artist: "Sandro Botticelli" },
  { title: "American Gothic", artist: "Grant Wood" },
  { title: "The Kiss", artist: "Gustav Klimt" },
  { title: "The Last Supper", artist: "Leonardo da Vinci" },
  { title: "Water Lilies", artist: "Claude Monet" },
  { title: "Composition VIII", artist: "Wassily Kandinsky" },
  { title: "The School of Athens", artist: "Raphael" },
  { title: "The Creation of Adam", artist: "Michelangelo" },
  { title: "The Dance", artist: "Henri Matisse" },
  { title: "The Arnolfini Portrait", artist: "Jan van Eyck" },
  { title: "Guernica", artist: "Pablo Picasso" },
  { title: "The Hay Wain", artist: "John Constable" },
  { title: "The Girl with the Broken Pitcher", artist: "Jean-Baptiste Greuze" },
  { title: "The Fighting Temeraire", artist: "J.M.W. Turner" },
  { title: "The Night Café", artist: "Vincent van Gogh" },
  { title: "The Two Fridas", artist: "Frida Kahlo" },
];
